### ISSUE TITLE
Add string interpolation

### ISSUE THREAD

**Issue by jackwilsdon** [felixmc/custom-logger#4]
`util.format` would probably be the best way to add this.

An example of the usage would be:

```js
log.info("Hello, %s!", "world");
```

**Comment by felixmc** [comment]
I like the idea, feel free to submit a PR, it might be a while before I get to implementing it myself

**Comment by jackwilsdon** [comment]
Should be fixed by #5. I added an option (`messageFormatting`) and disabled it by default as not to break the old functionality (joining all arguments using spaces).

**Comment by felixmc** [comment]
Fixed by pull request #5
